name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.6.0
  dio: ^5.7.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_storage: ^12.4.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.16
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  logger: ^2.5.0
  package_info_plus: ^8.1.2
  path_provider: ^2.1.5
  record: ^5.2.0
  riverpod_annotation: ^2.6.1
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.13
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutterfire_cli: ^1.0.0
  freezed: ^2.5.7
  go_router_builder: ^2.7.1
  json_serializable: ^6.9.0
  pedantic_mono: ^1.28.0
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
